# Site settings
title: Qianyang Peng | 彭乾旸
email: qp3@illinois.edu
github: QianyangPeng

description: > # this means to ignore newlines until "baseurl:"
  This is Qianyang Peng's homepage. Qianyang Peng is a senior student in IEEE honor class, Shanghai Jiaotong University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://qianyangpeng.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
